### ISSUE TITLE
Error: Unable to open password file /mosquitto/config/password.txt. Permission denied.

### ISSUE THREAD

**Issue by PvUtrix** [vvatelot/mosquitto-docker-compose#18]
The default user works, but I get an error when trying to add a new user by running the following command

docker compose exec mosquitto mosquitto_passwd -b /mosquitto/config/password.txt user password

Error: Unable to open password file /mosquitto/config/password.txt. Permission denied.

I have the following permissions by default
![image](https://user-images.githubusercontent.com/32957084/234400518-7188c8e3-d57b-4614-aff9-3d12db979390.png)

**Comment by vvatelot** [comment]
Hello @PvUtrix can you try to checkout the branch `fix/file-permissions` and follow the readme: https://github.com/vvatelot/mosquitto-docker-compose/tree/fix/file-permissions#readme ?

**Comment by PvUtrix** [comment]
Hello @vvatelot 
I'm getting an error when restarting the container
![Uploading image.png…]()

**Comment by vvatelot** [comment]
OK, I'll try to have a look this afternoon

**Comment by vvatelot** [comment]
Can you try to launch the command line 
```
UID=$UID GID=$GID USER=$USER docker compose up -d --build
```

**Comment by PvUtrix** [comment]
@vvatelot 
<img width="787" alt="image" src="https://user-images.githubusercontent.com/32957084/235367320-d48ed1fd-1314-42b2-b841-7b4057a968c8.png">

**Comment by vvatelot** [comment]
What if you run ?

```
UID=$(id -u) GID=$(id -g) USER=$$(id -un) docker compose up -d --build
```

**Comment by PvUtrix** [comment]
![image](https://user-images.githubusercontent.com/32957084/236134859-1d88727b-3b6e-4872-bb40-77babc844b94.png)

**Comment by vvatelot** [comment]
Can you try to pull the branch `fix/file-permissions` and to follow the new updated documentation: https://github.com/vvatelot/mosquitto-docker-compose/tree/fix/file-permissions ?

Now, with the `setup-project` step, we will create a `docker-compose.override.yml` file with UID and GID in it...

**Comment by stijnb1234** [comment]
![image](https://github.com/vvatelot/mosquitto-docker-compose/assets/27051051/3d38afb0-6584-4f50-8b62-2fd836d62bb3)
Same problem, get this when I run `make setup-project`.

**Comment by PvUtrix** [comment]
Same here 
<img width="1132" alt="image" src="https://github.com/vvatelot/mosquitto-docker-compose/assets/32957084/4720799b-e036-442c-98ac-415f150c00db">

**Comment by stijnb1234** [comment]
Thanks, works perfectly now!

**Comment by romanesko** [comment]
Helped me too!

**Comment by vvatelot** [comment]
@PvUtrix Can you confirm me that fixes your issue ?

**Comment by PvUtrix** [comment]
> @PvUtrix Can you confirm me that fixes your issue ?

all good now

**Comment by stijnb1234** [comment]
> > @PvUtrix Can you confirm me that fixes your issue ?
> 
> all good now

Please close the issue
